"""Adversarial Motion Priors discriminator.

The discriminator D(s, s') scores transitions:
  - "real" (~1): drawn from retargeted cat motion clips
  - "fake" (~0): generated by the policy in sim

The policy is then rewarded for producing transitions that fool the
discriminator -- this pushes its motion distribution toward the cat clips
without forcing it to track any specific clip.

Reference: Peng et al. 2021, "AMP: Adversarial Motion Priors for Stylized
Physics-Based Character Control" -- https://xbpeng.github.io/projects/AMP/

Implementation notes:
  - Architecture is a small MLP (default: [1024, 512] hidden) over the
    concatenated (s, s') feature vector.
  - Output is logit space; sigmoid is applied where needed.
  - Loss is least-squares GAN (LS-GAN), the variant Peng et al. use.
    Targets: 1.0 for real, -1.0 for fake. The style reward at inference
    time is `max(0, 1 - 0.25 * (1 - D(s, s'))^2)` per AMP eq. (5).
  - Gradient penalty (R1) is applied on real samples for training stability;
    coefficient 10.0 per the paper.

This module is JAX/Flax only -- it interoperates with brax's PPO loop.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

import flax.linen as nn
import jax
import jax.numpy as jnp


@dataclass
class AMPDiscConfig:
    hidden_sizes: Sequence[int] = (1024, 512)
    activation: str = "relu"             # "relu" | "silu" | "elu"
    obs_dim: int = 19                    # Go2 qpos: 7 root + 12 joints
    use_qvel: bool = False               # if True, observation is qpos + qvel
    grad_penalty_coef: float = 10.0      # R1 gradient penalty
    weight_decay: float = 1e-4
    style_reward_clip: float = 1.0       # max value of the per-step style reward
    style_reward_min: float = 0.0


def _get_activation(name: str):
    return {"relu": nn.relu, "silu": nn.silu, "elu": nn.elu}[name]


class AMPDiscriminator(nn.Module):
    """An MLP that takes concatenated (s, s') and outputs a single logit.

    Note: input feature is (2 * feat_dim,) where feat_dim is 19 if we use
    qpos only, or 19+18 = 37 if we use qpos + qvel.
    """

    config: AMPDiscConfig

    @nn.compact
    def __call__(self, transition: jnp.ndarray) -> jnp.ndarray:
        act = _get_activation(self.config.activation)
        x = transition
        for h in self.config.hidden_sizes:
            x = nn.Dense(features=h)(x)
            x = act(x)
        # Final layer: one logit per (s, s') pair.
        logit = nn.Dense(features=1)(x)
        return logit.squeeze(-1)


def make_transition_features(
    obs_t: jnp.ndarray,
    obs_tp1: jnp.ndarray,
) -> jnp.ndarray:
    """Concatenate (s, s') into a single feature vector for the discriminator.

    Both inputs are shaped (..., feat_dim); output is (..., 2 * feat_dim).
    """
    return jnp.concatenate([obs_t, obs_tp1], axis=-1)


# ---------------------------------------------------------------------------
# Losses
# ---------------------------------------------------------------------------


def lsgan_disc_loss(
    real_logits: jnp.ndarray,
    fake_logits: jnp.ndarray,
) -> jnp.ndarray:
    """Least-squares GAN discriminator loss (the variant AMP uses).

    Target = +1 for real, -1 for fake. Loss is mean squared distance from
    the target.
    """
    real_loss = jnp.mean(jnp.square(real_logits - 1.0))
    fake_loss = jnp.mean(jnp.square(fake_logits + 1.0))
    return 0.5 * (real_loss + fake_loss)


def grad_penalty(
    apply_fn,
    params,
    real_transitions: jnp.ndarray,
) -> jnp.ndarray:
    """R1 gradient penalty on real samples: penalize ||grad D(real)||^2.

    Encourages the discriminator to not become a step function near the data
    manifold. AMP uses this with coef ~10.
    """
    def disc_output(x):
        return apply_fn(params, x).sum()
    grads = jax.grad(disc_output)(real_transitions)
    sq = jnp.sum(jnp.square(grads), axis=-1)
    return jnp.mean(sq)


# ---------------------------------------------------------------------------
# Style reward (inference)
# ---------------------------------------------------------------------------


def style_reward(
    apply_fn,
    params,
    transitions: jnp.ndarray,
    cfg: AMPDiscConfig,
) -> jnp.ndarray:
    """Per-step style reward fed to PPO.

    Following AMP eq. (5):
      r_style(s, s') = max(0, 1 - 0.25 * (D(s, s') - 1)^2)

    This is zero when the policy looks fully real (D=1), and grows quadratically
    as the policy diverges from the real distribution. Bounded by `style_reward_clip`.
    """
    logits = apply_fn(params, transitions)
    raw = 1.0 - 0.25 * jnp.square(logits - 1.0)
    return jnp.clip(raw, a_min=cfg.style_reward_min, a_max=cfg.style_reward_clip)


# ---------------------------------------------------------------------------
# Init helpers
# ---------------------------------------------------------------------------


def init_discriminator(cfg: AMPDiscConfig, seed: int = 0):
    """Return (model, params, apply_fn) for the discriminator.

    Caller is responsible for plugging `params` into an optimizer (e.g. optax).
    """
    feat_dim = cfg.obs_dim
    if cfg.use_qvel:
        # qvel for Go2: 6 root (linear+angular velocity) + 12 joints = 18.
        feat_dim += cfg.obs_dim - 1
    model = AMPDiscriminator(config=cfg)
    rng = jax.random.PRNGKey(seed)
    dummy = jnp.zeros((1, 2 * feat_dim), dtype=jnp.float32)
    params = model.init(rng, dummy)
    return model, params, model.apply
